// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicSite.Models;

namespace MusicSite.Migrations
{
    [DbContext(typeof(AppDataBase))]
    [Migration("20220127234909_MusicSiteDb")]
    partial class MusicSiteDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "hdfsgkjhaskdhadsfk",
                            ConcurrencyStamp = "9cd19dad-62d7-4939-8edd-f41f7c6ef2e2",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "asdapsoid[pias",
                            ConcurrencyStamp = "66fa3940-2d10-412a-9f77-45918ce838e5",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "asdapsoid[pias"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "asdapsoid[pias"
                        },
                        new
                        {
                            UserId = "113dsad-adsasasd",
                            RoleId = "hdfsgkjhaskdhadsfk"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MusicSite.Models.Album", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("albumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("artistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("releaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            albumName = "The College Dropout",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2004, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "2",
                            albumName = "Late Registration",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2005, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "3",
                            albumName = "Graduation",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2007, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "4",
                            albumName = "808s & Heartbreak",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2008, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "5",
                            albumName = "My Beautiful Dark Twisted Fantasy",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2010, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "6",
                            albumName = "Yeezus",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2013, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "7",
                            albumName = "The Life of Pablo",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2016, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "8",
                            albumName = "ye",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "9",
                            albumName = "JESUS IS KING",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "10",
                            albumName = "Donda",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2021, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "11",
                            albumName = "Veteran",
                            artistName = "JPEGMAFIA",
                            releaseDate = new DateTime(2018, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MusicSite.Models.Review", b =>
                {
                    b.Property<string>("albumID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("userID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<byte>("rating")
                        .HasColumnType("tinyint");

                    b.Property<string>("reviewText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("albumID", "userID");

                    b.HasIndex("userID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            albumID = "1",
                            userID = "1",
                            ID = "1",
                            rating = (byte)5,
                            reviewText = "Good"
                        },
                        new
                        {
                            albumID = "1",
                            userID = "2",
                            ID = "1",
                            rating = (byte)3,
                            reviewText = "Mid"
                        },
                        new
                        {
                            albumID = "2",
                            userID = "1",
                            ID = "1",
                            rating = (byte)5,
                            reviewText = "Good"
                        },
                        new
                        {
                            albumID = "3",
                            userID = "1",
                            ID = "1",
                            rating = (byte)5,
                            reviewText = "Good"
                        },
                        new
                        {
                            albumID = "4",
                            userID = "1",
                            ID = "1",
                            rating = (byte)5,
                            reviewText = "Good"
                        },
                        new
                        {
                            albumID = "5",
                            userID = "1",
                            ID = "1",
                            rating = (byte)5,
                            reviewText = "Good"
                        },
                        new
                        {
                            albumID = "6",
                            userID = "1",
                            ID = "1",
                            rating = (byte)5,
                            reviewText = "Good"
                        },
                        new
                        {
                            albumID = "7",
                            userID = "1",
                            ID = "1",
                            rating = (byte)5,
                            reviewText = "Good"
                        },
                        new
                        {
                            albumID = "8",
                            userID = "1",
                            ID = "1",
                            rating = (byte)5,
                            reviewText = "Good"
                        },
                        new
                        {
                            albumID = "9",
                            userID = "1",
                            ID = "1",
                            rating = (byte)5,
                            reviewText = "Good"
                        },
                        new
                        {
                            albumID = "10",
                            userID = "1",
                            ID = "1",
                            rating = (byte)5,
                            reviewText = "Good"
                        },
                        new
                        {
                            albumID = "11",
                            userID = "1",
                            ID = "1",
                            rating = (byte)5,
                            reviewText = "Good"
                        });
                });

            modelBuilder.Entity("MusicSite.Models.Track.TrackDB", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AlbumID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrackLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrackNumberInAlbum")
                        .HasColumnType("int");

                    b.Property<string>("TrackTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AlbumID");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            AlbumID = "1",
                            TrackLength = "0:19",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Intro"
                        },
                        new
                        {
                            ID = "2",
                            AlbumID = "1",
                            TrackLength = "3:59",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "We Don't Care"
                        },
                        new
                        {
                            ID = "3",
                            AlbumID = "1",
                            TrackLength = "1:22",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Graduation Day"
                        },
                        new
                        {
                            ID = "4",
                            AlbumID = "1",
                            TrackLength = "3:43",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "All Falls Down"
                        },
                        new
                        {
                            ID = "5",
                            AlbumID = "1",
                            TrackLength = "1:09",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "I will Fly Away"
                        },
                        new
                        {
                            ID = "6",
                            AlbumID = "1",
                            TrackLength = "5:24",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Spaceship"
                        },
                        new
                        {
                            ID = "7",
                            AlbumID = "1",
                            TrackLength = "3:13",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Jesus Walks"
                        },
                        new
                        {
                            ID = "8",
                            AlbumID = "1",
                            TrackLength = "5:24",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Never Let Me Down"
                        },
                        new
                        {
                            ID = "9",
                            AlbumID = "1",
                            TrackLength = "4:49",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Get Em High"
                        },
                        new
                        {
                            ID = "10",
                            AlbumID = "1",
                            TrackLength = "0:46",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Workout Plan"
                        },
                        new
                        {
                            ID = "11",
                            AlbumID = "1",
                            TrackLength = "5:22",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "The New Workout Plan"
                        },
                        new
                        {
                            ID = "12",
                            AlbumID = "1",
                            TrackLength = "5:16",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "Slow Jamz"
                        },
                        new
                        {
                            ID = "13",
                            AlbumID = "1",
                            TrackLength = "4:06",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Breathe In Breathe Out"
                        },
                        new
                        {
                            ID = "14",
                            AlbumID = "1",
                            TrackLength = "1:18",
                            TrackNumberInAlbum = 14,
                            TrackTitle = "School Spirit Skit 1"
                        },
                        new
                        {
                            ID = "15",
                            AlbumID = "1",
                            TrackLength = "3:02",
                            TrackNumberInAlbum = 15,
                            TrackTitle = "School Spirit"
                        },
                        new
                        {
                            ID = "16",
                            AlbumID = "1",
                            TrackLength = "0:43",
                            TrackNumberInAlbum = 16,
                            TrackTitle = "School Spirit Skit 2"
                        },
                        new
                        {
                            ID = "17",
                            AlbumID = "1",
                            TrackLength = "0:53",
                            TrackNumberInAlbum = 17,
                            TrackTitle = "Lil Jimmy Skit"
                        },
                        new
                        {
                            ID = "18",
                            AlbumID = "1",
                            TrackLength = "4:26",
                            TrackNumberInAlbum = 18,
                            TrackTitle = "Two Words"
                        },
                        new
                        {
                            ID = "19",
                            AlbumID = "1",
                            TrackLength = "3:41",
                            TrackNumberInAlbum = 19,
                            TrackTitle = "Through the Wire"
                        },
                        new
                        {
                            ID = "20",
                            AlbumID = "1",
                            TrackLength = "4:38",
                            TrackNumberInAlbum = 20,
                            TrackTitle = "Family Business"
                        },
                        new
                        {
                            ID = "21",
                            AlbumID = "1",
                            TrackLength = "12:40",
                            TrackNumberInAlbum = 21,
                            TrackTitle = "Last Call"
                        },
                        new
                        {
                            ID = "22",
                            AlbumID = "2",
                            TrackLength = "0:41",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Wake Up Mr. West"
                        },
                        new
                        {
                            ID = "23",
                            AlbumID = "2",
                            TrackLength = "3:25",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Heard Em Say"
                        },
                        new
                        {
                            ID = "24",
                            AlbumID = "2",
                            TrackLength = "3:56",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Touch the Sky"
                        },
                        new
                        {
                            ID = "25",
                            AlbumID = "2",
                            TrackLength = "3:27",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Gold Digger"
                        },
                        new
                        {
                            ID = "26",
                            AlbumID = "2",
                            TrackLength = "0:33",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Skit #1"
                        },
                        new
                        {
                            ID = "27",
                            AlbumID = "2",
                            TrackLength = "4:32",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Drive Slow"
                        },
                        new
                        {
                            ID = "28",
                            AlbumID = "2",
                            TrackLength = "1:43",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "My Way Home"
                        },
                        new
                        {
                            ID = "29",
                            AlbumID = "2",
                            TrackLength = "4:31",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Crack Music"
                        },
                        new
                        {
                            ID = "30",
                            AlbumID = "2",
                            TrackLength = "4:05",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Roses"
                        },
                        new
                        {
                            ID = "31",
                            AlbumID = "2",
                            TrackLength = "3:19",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Bring Me Down"
                        },
                        new
                        {
                            ID = "32",
                            AlbumID = "2",
                            TrackLength = "4:27",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "Addiction"
                        },
                        new
                        {
                            ID = "33",
                            AlbumID = "2",
                            TrackLength = "0:31",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "Skit #2"
                        },
                        new
                        {
                            ID = "34",
                            AlbumID = "2",
                            TrackLength = "3:53",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Diamonds From Sierra Leone (Remix)"
                        },
                        new
                        {
                            ID = "35",
                            AlbumID = "2",
                            TrackLength = "7:28",
                            TrackNumberInAlbum = 14,
                            TrackTitle = "We Major"
                        },
                        new
                        {
                            ID = "36",
                            AlbumID = "2",
                            TrackLength = "0:24",
                            TrackNumberInAlbum = 15,
                            TrackTitle = "Skit #3"
                        },
                        new
                        {
                            ID = "37",
                            AlbumID = "2",
                            TrackLength = "5:05",
                            TrackNumberInAlbum = 16,
                            TrackTitle = "Hey Mama"
                        },
                        new
                        {
                            ID = "38",
                            AlbumID = "2",
                            TrackLength = "3:18",
                            TrackNumberInAlbum = 17,
                            TrackTitle = "Celebration"
                        },
                        new
                        {
                            ID = "39",
                            AlbumID = "2",
                            TrackLength = "1:19",
                            TrackNumberInAlbum = 18,
                            TrackTitle = "Skit #4"
                        },
                        new
                        {
                            ID = "40",
                            AlbumID = "2",
                            TrackLength = "5:32",
                            TrackNumberInAlbum = 19,
                            TrackTitle = "Gone"
                        },
                        new
                        {
                            ID = "41",
                            AlbumID = "2",
                            TrackLength = "3:58",
                            TrackNumberInAlbum = 20,
                            TrackTitle = "Diamonds From Sierra Leone [bonus track]"
                        },
                        new
                        {
                            ID = "42",
                            AlbumID = "2",
                            TrackLength = "3:50",
                            TrackNumberInAlbum = 21,
                            TrackTitle = "Late"
                        },
                        new
                        {
                            ID = "43",
                            AlbumID = "3",
                            TrackLength = "3:15",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Good Morning"
                        },
                        new
                        {
                            ID = "44",
                            AlbumID = "3",
                            TrackLength = "2:48",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Champion"
                        },
                        new
                        {
                            ID = "45",
                            AlbumID = "3",
                            TrackLength = "5:12",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Stronger"
                        },
                        new
                        {
                            ID = "46",
                            AlbumID = "3",
                            TrackLength = "4:03",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "I Wonder"
                        },
                        new
                        {
                            ID = "47",
                            AlbumID = "3",
                            TrackLength = "3:27",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Good Life"
                        },
                        new
                        {
                            ID = "48",
                            AlbumID = "3",
                            TrackLength = "4:32",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Cant Tell Me Nothing"
                        },
                        new
                        {
                            ID = "49",
                            AlbumID = "3",
                            TrackLength = "3:24",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Barry Bonds"
                        },
                        new
                        {
                            ID = "50",
                            AlbumID = "3",
                            TrackLength = "3:24",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Drunk and Hot Girls"
                        },
                        new
                        {
                            ID = "51",
                            AlbumID = "3",
                            TrackLength = "3:58",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Flashing Lights"
                        },
                        new
                        {
                            ID = "52",
                            AlbumID = "3",
                            TrackLength = "3:48",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Everything I Am"
                        },
                        new
                        {
                            ID = "53",
                            AlbumID = "3",
                            TrackLength = "3:33",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "The Glory"
                        },
                        new
                        {
                            ID = "54",
                            AlbumID = "3",
                            TrackLength = "3:24",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "Homecoming"
                        },
                        new
                        {
                            ID = "55",
                            AlbumID = "3",
                            TrackLength = "4:47",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Big Brother"
                        },
                        new
                        {
                            ID = "56",
                            AlbumID = "4",
                            TrackLength = "6:18",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Say You Will"
                        },
                        new
                        {
                            ID = "57",
                            AlbumID = "4",
                            TrackLength = "4:23",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Welcome to Heartbreak"
                        },
                        new
                        {
                            ID = "58",
                            AlbumID = "4",
                            TrackLength = "3:31",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Heartless"
                        },
                        new
                        {
                            ID = "59",
                            AlbumID = "4",
                            TrackLength = "3:58",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Amazing"
                        },
                        new
                        {
                            ID = "60",
                            AlbumID = "4",
                            TrackLength = "4:30",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Love Lockdown"
                        },
                        new
                        {
                            ID = "61",
                            AlbumID = "4",
                            TrackLength = "4:38",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Paranoid"
                        },
                        new
                        {
                            ID = "62",
                            AlbumID = "4",
                            TrackLength = "4:34",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "RoboCop"
                        },
                        new
                        {
                            ID = "63",
                            AlbumID = "4",
                            TrackLength = "3:10",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Street Lights"
                        },
                        new
                        {
                            ID = "64",
                            AlbumID = "4",
                            TrackLength = "3:59",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Bad News"
                        },
                        new
                        {
                            ID = "65",
                            AlbumID = "4",
                            TrackLength = "4:18",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "See You in My Nightmares"
                        },
                        new
                        {
                            ID = "66",
                            AlbumID = "4",
                            TrackLength = "2:44",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "Coldest Winter"
                        },
                        new
                        {
                            ID = "67",
                            AlbumID = "5",
                            TrackLength = "4:40",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Dark Fantasy"
                        },
                        new
                        {
                            ID = "68",
                            AlbumID = "5",
                            TrackLength = "5:57",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Gorgeous"
                        },
                        new
                        {
                            ID = "69",
                            AlbumID = "5",
                            TrackLength = "4:52",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Power"
                        },
                        new
                        {
                            ID = "70",
                            AlbumID = "5",
                            TrackLength = "1:02",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "All of the Lights (Interlude)"
                        },
                        new
                        {
                            ID = "71",
                            AlbumID = "5",
                            TrackLength = "4:59",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "All of the Lights"
                        },
                        new
                        {
                            ID = "72",
                            AlbumID = "5",
                            TrackLength = "6:18",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Monster"
                        },
                        new
                        {
                            ID = "73",
                            AlbumID = "5",
                            TrackLength = "6:38",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "So Appalled"
                        },
                        new
                        {
                            ID = "74",
                            AlbumID = "5",
                            TrackLength = "5:52",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Devil in a New Dress"
                        },
                        new
                        {
                            ID = "75",
                            AlbumID = "5",
                            TrackLength = "9:08",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Runaway"
                        },
                        new
                        {
                            ID = "76",
                            AlbumID = "5",
                            TrackLength = "5:27",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Hell of a Life"
                        },
                        new
                        {
                            ID = "77",
                            AlbumID = "5",
                            TrackLength = "7:49",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "Blame Game"
                        },
                        new
                        {
                            ID = "78",
                            AlbumID = "5",
                            TrackLength = "4:16",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "Lost in the World"
                        },
                        new
                        {
                            ID = "79",
                            AlbumID = "5",
                            TrackLength = "1:38",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Who Will Survive in America"
                        },
                        new
                        {
                            ID = "80",
                            AlbumID = "6",
                            TrackLength = "2:37",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "On Sight"
                        },
                        new
                        {
                            ID = "81",
                            AlbumID = "6",
                            TrackLength = "3:08",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Black Skinhead"
                        },
                        new
                        {
                            ID = "82",
                            AlbumID = "6",
                            TrackLength = "3:52",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "I Am a God"
                        },
                        new
                        {
                            ID = "83",
                            AlbumID = "6",
                            TrackLength = "4:16",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "New Slaves"
                        },
                        new
                        {
                            ID = "84",
                            AlbumID = "6",
                            TrackLength = "5:27",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Hold My Liquor"
                        },
                        new
                        {
                            ID = "85",
                            AlbumID = "6",
                            TrackLength = "3:55",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Im in It"
                        },
                        new
                        {
                            ID = "86",
                            AlbumID = "6",
                            TrackLength = "6:00",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Blood on the Leaves"
                        },
                        new
                        {
                            ID = "87",
                            AlbumID = "6",
                            TrackLength = "4:04",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Guilt Trip"
                        },
                        new
                        {
                            ID = "88",
                            AlbumID = "6",
                            TrackLength = "2:58",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Send It UpSend It Up"
                        },
                        new
                        {
                            ID = "89",
                            AlbumID = "6",
                            TrackLength = "3:49",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Bound 2"
                        },
                        new
                        {
                            ID = "90",
                            AlbumID = "7",
                            TrackLength = "5:20",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Ultralight Beam"
                        },
                        new
                        {
                            ID = "91",
                            AlbumID = "7",
                            TrackLength = "2:15",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Father Stretch My Hands, Pt. 1"
                        },
                        new
                        {
                            ID = "92",
                            AlbumID = "7",
                            TrackLength = "2:09",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Pt. 2"
                        },
                        new
                        {
                            ID = "93",
                            AlbumID = "7",
                            TrackLength = "3:14",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Famous"
                        },
                        new
                        {
                            ID = "94",
                            AlbumID = "7",
                            TrackLength = "2:35",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Feedback"
                        },
                        new
                        {
                            ID = "95",
                            AlbumID = "7",
                            TrackLength = "2:11",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Low Lights"
                        },
                        new
                        {
                            ID = "96",
                            AlbumID = "7",
                            TrackLength = "3:19",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Highlights"
                        },
                        new
                        {
                            ID = "97",
                            AlbumID = "7",
                            TrackLength = "2:02",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Freestyle 4"
                        },
                        new
                        {
                            ID = "98",
                            AlbumID = "7",
                            TrackLength = "0:44",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "I Love Kanye"
                        },
                        new
                        {
                            ID = "99",
                            AlbumID = "7",
                            TrackLength = "3:01",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Waves"
                        },
                        new
                        {
                            ID = "100",
                            AlbumID = "7",
                            TrackLength = "3:56",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "FML"
                        },
                        new
                        {
                            ID = "101",
                            AlbumID = "7",
                            TrackLength = "4:11",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "Real Friends"
                        },
                        new
                        {
                            ID = "102",
                            AlbumID = "7",
                            TrackLength = "3:59",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Wolves"
                        },
                        new
                        {
                            ID = "103",
                            AlbumID = "7",
                            TrackLength = "0:56",
                            TrackNumberInAlbum = 14,
                            TrackTitle = "Siiiiiiiiilver Surffffeeeeer Intermission"
                        },
                        new
                        {
                            ID = "104",
                            AlbumID = "7",
                            TrackLength = "5:25",
                            TrackNumberInAlbum = 15,
                            TrackTitle = "30 Hours"
                        },
                        new
                        {
                            ID = "105",
                            AlbumID = "7",
                            TrackLength = "6:14",
                            TrackNumberInAlbum = 16,
                            TrackTitle = "No More Parties in LA"
                        },
                        new
                        {
                            ID = "106",
                            AlbumID = "7",
                            TrackLength = "3:19",
                            TrackNumberInAlbum = 17,
                            TrackTitle = "Facts (Charlie Heat Version)"
                        },
                        new
                        {
                            ID = "107",
                            AlbumID = "7",
                            TrackLength = "3:13",
                            TrackNumberInAlbum = 18,
                            TrackTitle = "Fade"
                        },
                        new
                        {
                            ID = "108",
                            AlbumID = "8",
                            TrackLength = "4:34",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "I Thought About Killing You"
                        },
                        new
                        {
                            ID = "109",
                            AlbumID = "8",
                            TrackLength = "3:08",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Yikes"
                        },
                        new
                        {
                            ID = "110",
                            AlbumID = "8",
                            TrackLength = "2:25",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "All Mine"
                        },
                        new
                        {
                            ID = "111",
                            AlbumID = "8",
                            TrackLength = "3:25",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Wouldnt Leave"
                        },
                        new
                        {
                            ID = "112",
                            AlbumID = "8",
                            TrackLength = "2:03",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "No Mistakes"
                        },
                        new
                        {
                            ID = "113",
                            AlbumID = "8",
                            TrackLength = "4:31",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Ghost Town"
                        },
                        new
                        {
                            ID = "114",
                            AlbumID = "8",
                            TrackLength = "3:35",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Violent Crimes"
                        },
                        new
                        {
                            ID = "115",
                            AlbumID = "9",
                            TrackLength = "1:52",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Every Hour"
                        },
                        new
                        {
                            ID = "116",
                            AlbumID = "9",
                            TrackLength = "2:45",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Selah"
                        },
                        new
                        {
                            ID = "117",
                            AlbumID = "9",
                            TrackLength = "1:45",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Follow God"
                        },
                        new
                        {
                            ID = "118",
                            AlbumID = "9",
                            TrackLength = "2:32",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Closed on Sunday"
                        },
                        new
                        {
                            ID = "119",
                            AlbumID = "9",
                            TrackLength = "2:16",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "On God"
                        },
                        new
                        {
                            ID = "120",
                            AlbumID = "9",
                            TrackLength = "1:57",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Everything We Need"
                        },
                        new
                        {
                            ID = "121",
                            AlbumID = "9",
                            TrackLength = "2:48",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Water"
                        },
                        new
                        {
                            ID = "122",
                            AlbumID = "9",
                            TrackLength = "3:23",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "God Is"
                        },
                        new
                        {
                            ID = "123",
                            AlbumID = "9",
                            TrackLength = "3:23",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Hands On"
                        },
                        new
                        {
                            ID = "124",
                            AlbumID = "9",
                            TrackLength = "3:34",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Use This Gospel"
                        },
                        new
                        {
                            ID = "125",
                            AlbumID = "9",
                            TrackLength = "0:49",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "Jesus Is Lord"
                        });
                });

            modelBuilder.Entity("MusicSite.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            AccountCreationDate = new DateTime(2022, 1, 28, 0, 49, 8, 847, DateTimeKind.Local).AddTicks(4352),
                            ConcurrencyStamp = "55c93e83-32ce-4c25-a26f-6f141b0c1e62",
                            CreationDate = new DateTime(1999, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mateuszgalos@gmail.com",
                            EmailConfirmed = false,
                            LastName = "Galos",
                            LockoutEnabled = false,
                            Name = "Mateusz",
                            PasswordHash = "AQAAAAEAACcQAAAAENLAxThpZFLG18QfD7iVm7rPvN4PwFqICoLU43hI0P0cTBJvk1spWXu/5MsasFGvyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fdd484f0-944e-4db6-a820-e0ceabbebd47",
                            TwoFactorEnabled = false,
                            UserName = "MAgick90909"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            AccountCreationDate = new DateTime(2022, 1, 28, 0, 49, 8, 850, DateTimeKind.Local).AddTicks(3728),
                            ConcurrencyStamp = "fb390e0c-2985-46a8-ae59-50143d645a4e",
                            CreationDate = new DateTime(1997, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user2@gmail.com",
                            EmailConfirmed = false,
                            LastName = "Stefanowy",
                            LockoutEnabled = false,
                            Name = "Stefan",
                            PasswordHash = "AQAAAAEAACcQAAAAENLAxThpZFLG18QfD7iVm7rPvN4PwFqICoLU43hI0P0cTBJvk1spWXu/5MsasFGvyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bfa6f3dc-97e3-4ee1-b3f1-9cb835817423",
                            TwoFactorEnabled = false,
                            UserName = "User2"
                        },
                        new
                        {
                            Id = "113dsad-adsasasd",
                            AccessFailedCount = 0,
                            AccountCreationDate = new DateTime(2022, 1, 28, 0, 49, 8, 850, DateTimeKind.Local).AddTicks(3816),
                            ConcurrencyStamp = "1cef9b2d-23c8-4632-9a5a-06e93bdd93e5",
                            CreationDate = new DateTime(1999, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Admin@gmail.com",
                            EmailConfirmed = false,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAENLAxThpZFLG18QfD7iVm7rPvN4PwFqICoLU43hI0P0cTBJvk1spWXu/5MsasFGvyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "55fec80d-53f3-4b60-927b-42d3d5d5c045",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MusicSite.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MusicSite.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSite.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MusicSite.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicSite.Models.Review", b =>
                {
                    b.HasOne("MusicSite.Models.Album", "album")
                        .WithMany("albumReviews")
                        .HasForeignKey("albumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSite.Models.User", "author")
                        .WithMany("UserReviews")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("album");

                    b.Navigation("author");
                });

            modelBuilder.Entity("MusicSite.Models.Track.TrackDB", b =>
                {
                    b.HasOne("MusicSite.Models.Album", "Album")
                        .WithMany("albumTrackList")
                        .HasForeignKey("AlbumID");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MusicSite.Models.Album", b =>
                {
                    b.Navigation("albumReviews");

                    b.Navigation("albumTrackList");
                });

            modelBuilder.Entity("MusicSite.Models.User", b =>
                {
                    b.Navigation("UserReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
