// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MusicSite.Models;

namespace MusicSite.Migrations
{
    [DbContext(typeof(AppDataBase))]
    partial class AppDataBaseModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");

                    b.HasData(
                        new
                        {
                            Id = "hdfsgkjhaskdhadsfk",
                            ConcurrencyStamp = "bda77cd7-b421-4fb5-bc0d-b525da3fa99e",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "asdapsoid[pias",
                            ConcurrencyStamp = "9eb37d49-8865-478b-8d96-bbb60442e861",
                            Name = "User"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");

                    b.HasData(
                        new
                        {
                            UserId = "9734c7a3-1563-4db7-9148-4b829dddfb47",
                            RoleId = "asdapsoid[pias"
                        },
                        new
                        {
                            UserId = "3c6a2fad-ecd7-4a20-9079-feeaaf1ae2c1",
                            RoleId = "asdapsoid[pias"
                        },
                        new
                        {
                            UserId = "7178bf24-1894-480b-beb8-a733cb3f2eed",
                            RoleId = "hdfsgkjhaskdhadsfk"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("MusicSite.Models.Albums.Album", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("albumName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("artistName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("releaseDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            albumName = "The College Dropout",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2004, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "2",
                            albumName = "Late Registration",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2005, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "3",
                            albumName = "Graduation",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2007, 9, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "4",
                            albumName = "808s & Heartbreak",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2008, 11, 24, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "5",
                            albumName = "My Beautiful Dark Twisted Fantasy",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2010, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "6",
                            albumName = "Yeezus",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2013, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "7",
                            albumName = "The Life of Pablo",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2016, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "8",
                            albumName = "ye",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2018, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "9",
                            albumName = "JESUS IS KING",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2019, 10, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "10",
                            albumName = "Donda",
                            artistName = "Kanye West",
                            releaseDate = new DateTime(2021, 8, 29, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = "11",
                            albumName = "Veteran",
                            artistName = "JPEGMAFIA",
                            releaseDate = new DateTime(2018, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MusicSite.Models.Reviews.Review", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("albumID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("rating")
                        .HasColumnType("int");

                    b.Property<string>("reviewText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("albumID");

                    b.HasIndex("userID");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            ID = "fa87440d-1ce8-46cf-baee-5c9476fb97cf",
                            albumID = "1",
                            rating = 5,
                            reviewText = "Good",
                            userID = "3c6a2fad-ecd7-4a20-9079-feeaaf1ae2c1"
                        },
                        new
                        {
                            ID = "c307885f-a956-4fd1-8a23-4110a1c6e129",
                            albumID = "1",
                            rating = 3,
                            reviewText = "Mid",
                            userID = "9734c7a3-1563-4db7-9148-4b829dddfb47"
                        },
                        new
                        {
                            ID = "c80a3538-2c34-40ec-9d1d-1d1a629a2e5d",
                            albumID = "2",
                            rating = 5,
                            reviewText = "Good",
                            userID = "9734c7a3-1563-4db7-9148-4b829dddfb47"
                        },
                        new
                        {
                            ID = "62535928-abd7-4577-8e55-9bbeaf59ae63",
                            albumID = "3",
                            rating = 5,
                            reviewText = "Good",
                            userID = "9734c7a3-1563-4db7-9148-4b829dddfb47"
                        },
                        new
                        {
                            ID = "cb8bc8d2-f263-4139-bd0e-78470e70ec23",
                            albumID = "4",
                            rating = 5,
                            reviewText = "Good",
                            userID = "9734c7a3-1563-4db7-9148-4b829dddfb47"
                        },
                        new
                        {
                            ID = "d5508780-18ba-434c-b3d3-aeabc3e15e78",
                            albumID = "5",
                            rating = 5,
                            reviewText = "Good",
                            userID = "9734c7a3-1563-4db7-9148-4b829dddfb47"
                        },
                        new
                        {
                            ID = "f75db586-fcb3-4c0e-bc8c-37900e77d664",
                            albumID = "6",
                            rating = 5,
                            reviewText = "Good",
                            userID = "9734c7a3-1563-4db7-9148-4b829dddfb47"
                        },
                        new
                        {
                            ID = "68f7a425-495c-4137-82b3-7ccbd01f1e91",
                            albumID = "7",
                            rating = 5,
                            reviewText = "Good",
                            userID = "9734c7a3-1563-4db7-9148-4b829dddfb47"
                        },
                        new
                        {
                            ID = "37e4d800-5b83-4ed9-93f4-e7a0affe269c",
                            albumID = "8",
                            rating = 5,
                            reviewText = "Good",
                            userID = "9734c7a3-1563-4db7-9148-4b829dddfb47"
                        },
                        new
                        {
                            ID = "a89e9c5a-67f3-421b-aa4a-0e7b2d6b8b6e",
                            albumID = "9",
                            rating = 5,
                            reviewText = "Good",
                            userID = "9734c7a3-1563-4db7-9148-4b829dddfb47"
                        },
                        new
                        {
                            ID = "ac0c1ca5-954a-4fdd-b0d3-d1246352f2f4",
                            albumID = "10",
                            rating = 5,
                            reviewText = "Good",
                            userID = "9734c7a3-1563-4db7-9148-4b829dddfb47"
                        },
                        new
                        {
                            ID = "0803834e-26a5-4310-b272-46b330464283",
                            albumID = "11",
                            rating = 5,
                            reviewText = "Good",
                            userID = "9734c7a3-1563-4db7-9148-4b829dddfb47"
                        });
                });

            modelBuilder.Entity("MusicSite.Models.Track.TrackDB", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("AlbumID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TrackLength")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TrackNumberInAlbum")
                        .HasColumnType("int");

                    b.Property<string>("TrackTitle")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AlbumID");

                    b.ToTable("Tracks");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            AlbumID = "1",
                            TrackLength = "0:19",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Intro"
                        },
                        new
                        {
                            ID = "2",
                            AlbumID = "1",
                            TrackLength = "3:59",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "We Don't Care"
                        },
                        new
                        {
                            ID = "3",
                            AlbumID = "1",
                            TrackLength = "1:22",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Graduation Day"
                        },
                        new
                        {
                            ID = "4",
                            AlbumID = "1",
                            TrackLength = "3:43",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "All Falls Down"
                        },
                        new
                        {
                            ID = "5",
                            AlbumID = "1",
                            TrackLength = "1:09",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "I will Fly Away"
                        },
                        new
                        {
                            ID = "6",
                            AlbumID = "1",
                            TrackLength = "5:24",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Spaceship"
                        },
                        new
                        {
                            ID = "7",
                            AlbumID = "1",
                            TrackLength = "3:13",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Jesus Walks"
                        },
                        new
                        {
                            ID = "8",
                            AlbumID = "1",
                            TrackLength = "5:24",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Never Let Me Down"
                        },
                        new
                        {
                            ID = "9",
                            AlbumID = "1",
                            TrackLength = "4:49",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Get Em High"
                        },
                        new
                        {
                            ID = "10",
                            AlbumID = "1",
                            TrackLength = "0:46",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Workout Plan"
                        },
                        new
                        {
                            ID = "11",
                            AlbumID = "1",
                            TrackLength = "5:22",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "The New Workout Plan"
                        },
                        new
                        {
                            ID = "12",
                            AlbumID = "1",
                            TrackLength = "5:16",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "Slow Jamz"
                        },
                        new
                        {
                            ID = "13",
                            AlbumID = "1",
                            TrackLength = "4:06",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Breathe In Breathe Out"
                        },
                        new
                        {
                            ID = "14",
                            AlbumID = "1",
                            TrackLength = "1:18",
                            TrackNumberInAlbum = 14,
                            TrackTitle = "School Spirit Skit 1"
                        },
                        new
                        {
                            ID = "15",
                            AlbumID = "1",
                            TrackLength = "3:02",
                            TrackNumberInAlbum = 15,
                            TrackTitle = "School Spirit"
                        },
                        new
                        {
                            ID = "16",
                            AlbumID = "1",
                            TrackLength = "0:43",
                            TrackNumberInAlbum = 16,
                            TrackTitle = "School Spirit Skit 2"
                        },
                        new
                        {
                            ID = "17",
                            AlbumID = "1",
                            TrackLength = "0:53",
                            TrackNumberInAlbum = 17,
                            TrackTitle = "Lil Jimmy Skit"
                        },
                        new
                        {
                            ID = "18",
                            AlbumID = "1",
                            TrackLength = "4:26",
                            TrackNumberInAlbum = 18,
                            TrackTitle = "Two Words"
                        },
                        new
                        {
                            ID = "19",
                            AlbumID = "1",
                            TrackLength = "3:41",
                            TrackNumberInAlbum = 19,
                            TrackTitle = "Through the Wire"
                        },
                        new
                        {
                            ID = "20",
                            AlbumID = "1",
                            TrackLength = "4:38",
                            TrackNumberInAlbum = 20,
                            TrackTitle = "Family Business"
                        },
                        new
                        {
                            ID = "21",
                            AlbumID = "1",
                            TrackLength = "12:40",
                            TrackNumberInAlbum = 21,
                            TrackTitle = "Last Call"
                        },
                        new
                        {
                            ID = "22",
                            AlbumID = "2",
                            TrackLength = "0:41",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Wake Up Mr. West"
                        },
                        new
                        {
                            ID = "23",
                            AlbumID = "2",
                            TrackLength = "3:25",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Heard Em Say"
                        },
                        new
                        {
                            ID = "24",
                            AlbumID = "2",
                            TrackLength = "3:56",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Touch the Sky"
                        },
                        new
                        {
                            ID = "25",
                            AlbumID = "2",
                            TrackLength = "3:27",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Gold Digger"
                        },
                        new
                        {
                            ID = "26",
                            AlbumID = "2",
                            TrackLength = "0:33",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Skit #1"
                        },
                        new
                        {
                            ID = "27",
                            AlbumID = "2",
                            TrackLength = "4:32",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Drive Slow"
                        },
                        new
                        {
                            ID = "28",
                            AlbumID = "2",
                            TrackLength = "1:43",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "My Way Home"
                        },
                        new
                        {
                            ID = "29",
                            AlbumID = "2",
                            TrackLength = "4:31",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Crack Music"
                        },
                        new
                        {
                            ID = "30",
                            AlbumID = "2",
                            TrackLength = "4:05",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Roses"
                        },
                        new
                        {
                            ID = "31",
                            AlbumID = "2",
                            TrackLength = "3:19",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Bring Me Down"
                        },
                        new
                        {
                            ID = "32",
                            AlbumID = "2",
                            TrackLength = "4:27",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "Addiction"
                        },
                        new
                        {
                            ID = "33",
                            AlbumID = "2",
                            TrackLength = "0:31",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "Skit #2"
                        },
                        new
                        {
                            ID = "34",
                            AlbumID = "2",
                            TrackLength = "3:53",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Diamonds From Sierra Leone (Remix)"
                        },
                        new
                        {
                            ID = "35",
                            AlbumID = "2",
                            TrackLength = "7:28",
                            TrackNumberInAlbum = 14,
                            TrackTitle = "We Major"
                        },
                        new
                        {
                            ID = "36",
                            AlbumID = "2",
                            TrackLength = "0:24",
                            TrackNumberInAlbum = 15,
                            TrackTitle = "Skit #3"
                        },
                        new
                        {
                            ID = "37",
                            AlbumID = "2",
                            TrackLength = "5:05",
                            TrackNumberInAlbum = 16,
                            TrackTitle = "Hey Mama"
                        },
                        new
                        {
                            ID = "38",
                            AlbumID = "2",
                            TrackLength = "3:18",
                            TrackNumberInAlbum = 17,
                            TrackTitle = "Celebration"
                        },
                        new
                        {
                            ID = "39",
                            AlbumID = "2",
                            TrackLength = "1:19",
                            TrackNumberInAlbum = 18,
                            TrackTitle = "Skit #4"
                        },
                        new
                        {
                            ID = "40",
                            AlbumID = "2",
                            TrackLength = "5:32",
                            TrackNumberInAlbum = 19,
                            TrackTitle = "Gone"
                        },
                        new
                        {
                            ID = "41",
                            AlbumID = "2",
                            TrackLength = "3:58",
                            TrackNumberInAlbum = 20,
                            TrackTitle = "Diamonds From Sierra Leone [bonus track]"
                        },
                        new
                        {
                            ID = "42",
                            AlbumID = "2",
                            TrackLength = "3:50",
                            TrackNumberInAlbum = 21,
                            TrackTitle = "Late"
                        },
                        new
                        {
                            ID = "43",
                            AlbumID = "3",
                            TrackLength = "3:15",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Good Morning"
                        },
                        new
                        {
                            ID = "44",
                            AlbumID = "3",
                            TrackLength = "2:48",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Champion"
                        },
                        new
                        {
                            ID = "45",
                            AlbumID = "3",
                            TrackLength = "5:12",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Stronger"
                        },
                        new
                        {
                            ID = "46",
                            AlbumID = "3",
                            TrackLength = "4:03",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "I Wonder"
                        },
                        new
                        {
                            ID = "47",
                            AlbumID = "3",
                            TrackLength = "3:27",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Good Life"
                        },
                        new
                        {
                            ID = "48",
                            AlbumID = "3",
                            TrackLength = "4:32",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Cant Tell Me Nothing"
                        },
                        new
                        {
                            ID = "49",
                            AlbumID = "3",
                            TrackLength = "3:24",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Barry Bonds"
                        },
                        new
                        {
                            ID = "50",
                            AlbumID = "3",
                            TrackLength = "3:24",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Drunk and Hot Girls"
                        },
                        new
                        {
                            ID = "51",
                            AlbumID = "3",
                            TrackLength = "3:58",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Flashing Lights"
                        },
                        new
                        {
                            ID = "52",
                            AlbumID = "3",
                            TrackLength = "3:48",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Everything I Am"
                        },
                        new
                        {
                            ID = "53",
                            AlbumID = "3",
                            TrackLength = "3:33",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "The Glory"
                        },
                        new
                        {
                            ID = "54",
                            AlbumID = "3",
                            TrackLength = "3:24",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "Homecoming"
                        },
                        new
                        {
                            ID = "55",
                            AlbumID = "3",
                            TrackLength = "4:47",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Big Brother"
                        },
                        new
                        {
                            ID = "56",
                            AlbumID = "4",
                            TrackLength = "6:18",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Say You Will"
                        },
                        new
                        {
                            ID = "57",
                            AlbumID = "4",
                            TrackLength = "4:23",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Welcome to Heartbreak"
                        },
                        new
                        {
                            ID = "58",
                            AlbumID = "4",
                            TrackLength = "3:31",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Heartless"
                        },
                        new
                        {
                            ID = "59",
                            AlbumID = "4",
                            TrackLength = "3:58",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Amazing"
                        },
                        new
                        {
                            ID = "60",
                            AlbumID = "4",
                            TrackLength = "4:30",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Love Lockdown"
                        },
                        new
                        {
                            ID = "61",
                            AlbumID = "4",
                            TrackLength = "4:38",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Paranoid"
                        },
                        new
                        {
                            ID = "62",
                            AlbumID = "4",
                            TrackLength = "4:34",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "RoboCop"
                        },
                        new
                        {
                            ID = "63",
                            AlbumID = "4",
                            TrackLength = "3:10",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Street Lights"
                        },
                        new
                        {
                            ID = "64",
                            AlbumID = "4",
                            TrackLength = "3:59",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Bad News"
                        },
                        new
                        {
                            ID = "65",
                            AlbumID = "4",
                            TrackLength = "4:18",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "See You in My Nightmares"
                        },
                        new
                        {
                            ID = "66",
                            AlbumID = "4",
                            TrackLength = "2:44",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "Coldest Winter"
                        },
                        new
                        {
                            ID = "67",
                            AlbumID = "5",
                            TrackLength = "4:40",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Dark Fantasy"
                        },
                        new
                        {
                            ID = "68",
                            AlbumID = "5",
                            TrackLength = "5:57",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Gorgeous"
                        },
                        new
                        {
                            ID = "69",
                            AlbumID = "5",
                            TrackLength = "4:52",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Power"
                        },
                        new
                        {
                            ID = "70",
                            AlbumID = "5",
                            TrackLength = "1:02",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "All of the Lights (Interlude)"
                        },
                        new
                        {
                            ID = "71",
                            AlbumID = "5",
                            TrackLength = "4:59",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "All of the Lights"
                        },
                        new
                        {
                            ID = "72",
                            AlbumID = "5",
                            TrackLength = "6:18",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Monster"
                        },
                        new
                        {
                            ID = "73",
                            AlbumID = "5",
                            TrackLength = "6:38",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "So Appalled"
                        },
                        new
                        {
                            ID = "74",
                            AlbumID = "5",
                            TrackLength = "5:52",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Devil in a New Dress"
                        },
                        new
                        {
                            ID = "75",
                            AlbumID = "5",
                            TrackLength = "9:08",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Runaway"
                        },
                        new
                        {
                            ID = "76",
                            AlbumID = "5",
                            TrackLength = "5:27",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Hell of a Life"
                        },
                        new
                        {
                            ID = "77",
                            AlbumID = "5",
                            TrackLength = "7:49",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "Blame Game"
                        },
                        new
                        {
                            ID = "78",
                            AlbumID = "5",
                            TrackLength = "4:16",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "Lost in the World"
                        },
                        new
                        {
                            ID = "79",
                            AlbumID = "5",
                            TrackLength = "1:38",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Who Will Survive in America"
                        },
                        new
                        {
                            ID = "80",
                            AlbumID = "6",
                            TrackLength = "2:37",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "On Sight"
                        },
                        new
                        {
                            ID = "81",
                            AlbumID = "6",
                            TrackLength = "3:08",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Black Skinhead"
                        },
                        new
                        {
                            ID = "82",
                            AlbumID = "6",
                            TrackLength = "3:52",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "I Am a God"
                        },
                        new
                        {
                            ID = "83",
                            AlbumID = "6",
                            TrackLength = "4:16",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "New Slaves"
                        },
                        new
                        {
                            ID = "84",
                            AlbumID = "6",
                            TrackLength = "5:27",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Hold My Liquor"
                        },
                        new
                        {
                            ID = "85",
                            AlbumID = "6",
                            TrackLength = "3:55",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Im in It"
                        },
                        new
                        {
                            ID = "86",
                            AlbumID = "6",
                            TrackLength = "6:00",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Blood on the Leaves"
                        },
                        new
                        {
                            ID = "87",
                            AlbumID = "6",
                            TrackLength = "4:04",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Guilt Trip"
                        },
                        new
                        {
                            ID = "88",
                            AlbumID = "6",
                            TrackLength = "2:58",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Send It UpSend It Up"
                        },
                        new
                        {
                            ID = "89",
                            AlbumID = "6",
                            TrackLength = "3:49",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Bound 2"
                        },
                        new
                        {
                            ID = "90",
                            AlbumID = "7",
                            TrackLength = "5:20",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Ultralight Beam"
                        },
                        new
                        {
                            ID = "91",
                            AlbumID = "7",
                            TrackLength = "2:15",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Father Stretch My Hands, Pt. 1"
                        },
                        new
                        {
                            ID = "92",
                            AlbumID = "7",
                            TrackLength = "2:09",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Pt. 2"
                        },
                        new
                        {
                            ID = "93",
                            AlbumID = "7",
                            TrackLength = "3:14",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Famous"
                        },
                        new
                        {
                            ID = "94",
                            AlbumID = "7",
                            TrackLength = "2:35",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Feedback"
                        },
                        new
                        {
                            ID = "95",
                            AlbumID = "7",
                            TrackLength = "2:11",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Low Lights"
                        },
                        new
                        {
                            ID = "96",
                            AlbumID = "7",
                            TrackLength = "3:19",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Highlights"
                        },
                        new
                        {
                            ID = "97",
                            AlbumID = "7",
                            TrackLength = "2:02",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "Freestyle 4"
                        },
                        new
                        {
                            ID = "98",
                            AlbumID = "7",
                            TrackLength = "0:44",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "I Love Kanye"
                        },
                        new
                        {
                            ID = "99",
                            AlbumID = "7",
                            TrackLength = "3:01",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Waves"
                        },
                        new
                        {
                            ID = "100",
                            AlbumID = "7",
                            TrackLength = "3:56",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "FML"
                        },
                        new
                        {
                            ID = "101",
                            AlbumID = "7",
                            TrackLength = "4:11",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "Real Friends"
                        },
                        new
                        {
                            ID = "102",
                            AlbumID = "7",
                            TrackLength = "3:59",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Wolves"
                        },
                        new
                        {
                            ID = "103",
                            AlbumID = "7",
                            TrackLength = "0:56",
                            TrackNumberInAlbum = 14,
                            TrackTitle = "Siiiiiiiiilver Surffffeeeeer Intermission"
                        },
                        new
                        {
                            ID = "104",
                            AlbumID = "7",
                            TrackLength = "5:25",
                            TrackNumberInAlbum = 15,
                            TrackTitle = "30 Hours"
                        },
                        new
                        {
                            ID = "105",
                            AlbumID = "7",
                            TrackLength = "6:14",
                            TrackNumberInAlbum = 16,
                            TrackTitle = "No More Parties in LA"
                        },
                        new
                        {
                            ID = "106",
                            AlbumID = "7",
                            TrackLength = "3:19",
                            TrackNumberInAlbum = 17,
                            TrackTitle = "Facts (Charlie Heat Version)"
                        },
                        new
                        {
                            ID = "107",
                            AlbumID = "7",
                            TrackLength = "3:13",
                            TrackNumberInAlbum = 18,
                            TrackTitle = "Fade"
                        },
                        new
                        {
                            ID = "108",
                            AlbumID = "8",
                            TrackLength = "4:34",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "I Thought About Killing You"
                        },
                        new
                        {
                            ID = "109",
                            AlbumID = "8",
                            TrackLength = "3:08",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Yikes"
                        },
                        new
                        {
                            ID = "110",
                            AlbumID = "8",
                            TrackLength = "2:25",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "All Mine"
                        },
                        new
                        {
                            ID = "111",
                            AlbumID = "8",
                            TrackLength = "3:25",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Wouldnt Leave"
                        },
                        new
                        {
                            ID = "112",
                            AlbumID = "8",
                            TrackLength = "2:03",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "No Mistakes"
                        },
                        new
                        {
                            ID = "113",
                            AlbumID = "8",
                            TrackLength = "4:31",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Ghost Town"
                        },
                        new
                        {
                            ID = "114",
                            AlbumID = "8",
                            TrackLength = "3:35",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Violent Crimes"
                        },
                        new
                        {
                            ID = "115",
                            AlbumID = "9",
                            TrackLength = "1:52",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Every Hour"
                        },
                        new
                        {
                            ID = "116",
                            AlbumID = "9",
                            TrackLength = "2:45",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Selah"
                        },
                        new
                        {
                            ID = "117",
                            AlbumID = "9",
                            TrackLength = "1:45",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Follow God"
                        },
                        new
                        {
                            ID = "118",
                            AlbumID = "9",
                            TrackLength = "2:32",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Closed on Sunday"
                        },
                        new
                        {
                            ID = "119",
                            AlbumID = "9",
                            TrackLength = "2:16",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "On God"
                        },
                        new
                        {
                            ID = "120",
                            AlbumID = "9",
                            TrackLength = "1:57",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Everything We Need"
                        },
                        new
                        {
                            ID = "121",
                            AlbumID = "9",
                            TrackLength = "2:48",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Water"
                        },
                        new
                        {
                            ID = "122",
                            AlbumID = "9",
                            TrackLength = "3:23",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "God Is"
                        },
                        new
                        {
                            ID = "123",
                            AlbumID = "9",
                            TrackLength = "3:23",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Hands On"
                        },
                        new
                        {
                            ID = "124",
                            AlbumID = "9",
                            TrackLength = "3:34",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Use This Gospel"
                        },
                        new
                        {
                            ID = "125",
                            AlbumID = "9",
                            TrackLength = "0:49",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "Jesus Is Lord"
                        },
                        new
                        {
                            ID = "126",
                            AlbumID = "10",
                            TrackLength = "0:52",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "Donda Chant"
                        },
                        new
                        {
                            ID = "127",
                            AlbumID = "10",
                            TrackLength = "4:57",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Jail"
                        },
                        new
                        {
                            ID = "128",
                            AlbumID = "10",
                            TrackLength = "5:33",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "God Breathed"
                        },
                        new
                        {
                            ID = "129",
                            AlbumID = "10",
                            TrackLength = "5:39",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Off the Grid"
                        },
                        new
                        {
                            ID = "130",
                            AlbumID = "10",
                            TrackLength = "4:03",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Hurricane"
                        },
                        new
                        {
                            ID = "131",
                            AlbumID = "10",
                            TrackLength = "3:46",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "Praise God"
                        },
                        new
                        {
                            ID = "132",
                            AlbumID = "10",
                            TrackLength = "3:15",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Jonah"
                        },
                        new
                        {
                            ID = "133",
                            AlbumID = "10",
                            TrackLength = "3:24",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "OK OK"
                        },
                        new
                        {
                            ID = "134",
                            AlbumID = "10",
                            TrackLength = "2:27",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Junya"
                        },
                        new
                        {
                            ID = "135",
                            AlbumID = "10",
                            TrackLength = "4:02",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Believe What I Say"
                        },
                        new
                        {
                            ID = "136",
                            AlbumID = "10",
                            TrackLength = "3:17",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "24"
                        },
                        new
                        {
                            ID = "137",
                            AlbumID = "10",
                            TrackLength = "3:18",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "Remote Control"
                        },
                        new
                        {
                            ID = "138",
                            AlbumID = "10",
                            TrackLength = "2:36",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Moon"
                        },
                        new
                        {
                            ID = "139",
                            AlbumID = "10",
                            TrackLength = "2:25",
                            TrackNumberInAlbum = 14,
                            TrackTitle = "Heaven and Hell"
                        },
                        new
                        {
                            ID = "140",
                            AlbumID = "10",
                            TrackLength = "2:08",
                            TrackNumberInAlbum = 15,
                            TrackTitle = "Donda"
                        },
                        new
                        {
                            ID = "141",
                            AlbumID = "10",
                            TrackLength = "3:41",
                            TrackNumberInAlbum = 16,
                            TrackTitle = "Keep My Spirit Alive"
                        },
                        new
                        {
                            ID = "142",
                            AlbumID = "10",
                            TrackLength = "8:58",
                            TrackNumberInAlbum = 17,
                            TrackTitle = "Jesus Lord"
                        },
                        new
                        {
                            ID = "143",
                            AlbumID = "10",
                            TrackLength = "3:03",
                            TrackNumberInAlbum = 18,
                            TrackTitle = "New Again"
                        },
                        new
                        {
                            ID = "144",
                            AlbumID = "10",
                            TrackLength = "1:44",
                            TrackNumberInAlbum = 19,
                            TrackTitle = "Tell the Vision"
                        },
                        new
                        {
                            ID = "145",
                            AlbumID = "10",
                            TrackLength = "2:42",
                            TrackNumberInAlbum = 20,
                            TrackTitle = "Lord I Need You"
                        },
                        new
                        {
                            ID = "146",
                            AlbumID = "10",
                            TrackLength = "5:58",
                            TrackNumberInAlbum = 21,
                            TrackTitle = "Pure Souls"
                        },
                        new
                        {
                            ID = "147",
                            AlbumID = "10",
                            TrackLength = "5:10",
                            TrackNumberInAlbum = 22,
                            TrackTitle = "Come to Life"
                        },
                        new
                        {
                            ID = "148",
                            AlbumID = "10",
                            TrackLength = "2:57",
                            TrackNumberInAlbum = 23,
                            TrackTitle = "No Child Left Behind"
                        },
                        new
                        {
                            ID = "149",
                            AlbumID = "10",
                            TrackLength = "4:57",
                            TrackNumberInAlbum = 24,
                            TrackTitle = "Jail Pt 2"
                        },
                        new
                        {
                            ID = "150",
                            AlbumID = "10",
                            TrackLength = "3:24",
                            TrackNumberInAlbum = 25,
                            TrackTitle = "OK OK Pt 2"
                        },
                        new
                        {
                            ID = "151",
                            AlbumID = "10",
                            TrackLength = "3:02",
                            TrackNumberInAlbum = 26,
                            TrackTitle = "Junya Pt 2"
                        },
                        new
                        {
                            ID = "152",
                            AlbumID = "10",
                            TrackLength = "11:30",
                            TrackNumberInAlbum = 27,
                            TrackTitle = "Jesus Lord Pt 2"
                        },
                        new
                        {
                            ID = "153",
                            AlbumID = "11",
                            TrackLength = "2:37",
                            TrackNumberInAlbum = 1,
                            TrackTitle = "1539 N. Calvert"
                        },
                        new
                        {
                            ID = "154",
                            AlbumID = "11",
                            TrackLength = "2:31",
                            TrackNumberInAlbum = 2,
                            TrackTitle = "Real Nega"
                        },
                        new
                        {
                            ID = "155",
                            AlbumID = "11",
                            TrackLength = "3:18",
                            TrackNumberInAlbum = 3,
                            TrackTitle = "Thug Tears"
                        },
                        new
                        {
                            ID = "156",
                            AlbumID = "11",
                            TrackLength = "1:26",
                            TrackNumberInAlbum = 4,
                            TrackTitle = "Dayum"
                        },
                        new
                        {
                            ID = "157",
                            AlbumID = "11",
                            TrackLength = "2:34",
                            TrackNumberInAlbum = 5,
                            TrackTitle = "Baby I'm Bleeding"
                        },
                        new
                        {
                            ID = "158",
                            AlbumID = "11",
                            TrackLength = "1:34",
                            TrackNumberInAlbum = 6,
                            TrackTitle = "My Thoughts on Neogaf Dying"
                        },
                        new
                        {
                            ID = "159",
                            AlbumID = "11",
                            TrackLength = "3:08",
                            TrackNumberInAlbum = 7,
                            TrackTitle = "Rock N Roll Is Dead"
                        },
                        new
                        {
                            ID = "160",
                            AlbumID = "11",
                            TrackLength = "3:15",
                            TrackNumberInAlbum = 8,
                            TrackTitle = "DD Form 214"
                        },
                        new
                        {
                            ID = "161",
                            AlbumID = "11",
                            TrackLength = "2:41",
                            TrackNumberInAlbum = 9,
                            TrackTitle = "Germs"
                        },
                        new
                        {
                            ID = "162",
                            AlbumID = "11",
                            TrackLength = "1:20",
                            TrackNumberInAlbum = 10,
                            TrackTitle = "Libtard Anthem"
                        },
                        new
                        {
                            ID = "163",
                            AlbumID = "11",
                            TrackLength = "3:00",
                            TrackNumberInAlbum = 11,
                            TrackTitle = "Panic Emoji"
                        },
                        new
                        {
                            ID = "164",
                            AlbumID = "11",
                            TrackLength = "1:23",
                            TrackNumberInAlbum = 12,
                            TrackTitle = "DJ Snitch Interlude"
                        },
                        new
                        {
                            ID = "165",
                            AlbumID = "11",
                            TrackLength = "2:04",
                            TrackNumberInAlbum = 13,
                            TrackTitle = "Whole Foods"
                        },
                        new
                        {
                            ID = "166",
                            AlbumID = "11",
                            TrackLength = "1:57",
                            TrackNumberInAlbum = 14,
                            TrackTitle = "Macaulay Culkin"
                        },
                        new
                        {
                            ID = "167",
                            AlbumID = "11",
                            TrackLength = "3:33",
                            TrackNumberInAlbum = 15,
                            TrackTitle = "Williamsburg"
                        },
                        new
                        {
                            ID = "168",
                            AlbumID = "11",
                            TrackLength = "1:26",
                            TrackNumberInAlbum = 16,
                            TrackTitle = "I Cannot Wait Until Morrissey Dies"
                        },
                        new
                        {
                            ID = "169",
                            AlbumID = "11",
                            TrackLength = "4:43",
                            TrackNumberInAlbum = 17,
                            TrackTitle = "Rainbow Six"
                        },
                        new
                        {
                            ID = "170",
                            AlbumID = "11",
                            TrackLength = "2:28",
                            TrackNumberInAlbum = 18,
                            TrackTitle = "1488"
                        },
                        new
                        {
                            ID = "171",
                            AlbumID = "11",
                            TrackLength = "2:15",
                            TrackNumberInAlbum = 19,
                            TrackTitle = "Curb Stomp"
                        });
                });

            modelBuilder.Entity("MusicSite.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("AccountCreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasData(
                        new
                        {
                            Id = "9734c7a3-1563-4db7-9148-4b829dddfb47",
                            AccessFailedCount = 0,
                            AccountCreationDate = new DateTime(2022, 1, 28, 17, 9, 17, 542, DateTimeKind.Local).AddTicks(5137),
                            ConcurrencyStamp = "63a5f1ba-9367-4608-a3c1-60128df02856",
                            CreationDate = new DateTime(1999, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mateuszgalos@gmail.com",
                            EmailConfirmed = false,
                            LastName = "Galos",
                            LockoutEnabled = false,
                            Name = "Mateusz",
                            NormalizedUserName = "MAGICK90909",
                            PasswordHash = "AQAAAAEAACcQAAAAENLAxThpZFLG18QfD7iVm7rPvN4PwFqICoLU43hI0P0cTBJvk1spWXu/5MsasFGvyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "31ec3e16-ce57-4b3e-bd08-8d1041fe81a1",
                            TwoFactorEnabled = false,
                            UserName = "MAgick90909"
                        },
                        new
                        {
                            Id = "3c6a2fad-ecd7-4a20-9079-feeaaf1ae2c1",
                            AccessFailedCount = 0,
                            AccountCreationDate = new DateTime(2022, 1, 28, 17, 9, 17, 545, DateTimeKind.Local).AddTicks(6098),
                            ConcurrencyStamp = "cc9ca206-33fc-4bb9-b7de-5b6ee7270dc4",
                            CreationDate = new DateTime(1997, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "user2@gmail.com",
                            EmailConfirmed = false,
                            LastName = "Stefanowy",
                            LockoutEnabled = false,
                            Name = "Stefan",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAEAACcQAAAAENLAxThpZFLG18QfD7iVm7rPvN4PwFqICoLU43hI0P0cTBJvk1spWXu/5MsasFGvyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5b25125e-b2b9-4025-b000-aea0ec729172",
                            TwoFactorEnabled = false,
                            UserName = "User2"
                        },
                        new
                        {
                            Id = "7178bf24-1894-480b-beb8-a733cb3f2eed",
                            AccessFailedCount = 0,
                            AccountCreationDate = new DateTime(2022, 1, 28, 17, 9, 17, 545, DateTimeKind.Local).AddTicks(6321),
                            ConcurrencyStamp = "2422bbc0-79e6-43eb-9dab-7d7db1aa02df",
                            CreationDate = new DateTime(1999, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "Admin@gmail.com",
                            EmailConfirmed = false,
                            LastName = "Admin",
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAEAACcQAAAAENLAxThpZFLG18QfD7iVm7rPvN4PwFqICoLU43hI0P0cTBJvk1spWXu/5MsasFGvyA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "66c3d6cc-2249-48b5-9b2f-13ed5c93ee9a",
                            TwoFactorEnabled = false,
                            UserName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MusicSite.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MusicSite.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSite.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MusicSite.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MusicSite.Models.Reviews.Review", b =>
                {
                    b.HasOne("MusicSite.Models.Albums.Album", "album")
                        .WithMany("albumReviews")
                        .HasForeignKey("albumID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MusicSite.Models.User", "author")
                        .WithMany("UserReviews")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("album");

                    b.Navigation("author");
                });

            modelBuilder.Entity("MusicSite.Models.Track.TrackDB", b =>
                {
                    b.HasOne("MusicSite.Models.Albums.Album", "Album")
                        .WithMany("albumTrackList")
                        .HasForeignKey("AlbumID");

                    b.Navigation("Album");
                });

            modelBuilder.Entity("MusicSite.Models.Albums.Album", b =>
                {
                    b.Navigation("albumReviews");

                    b.Navigation("albumTrackList");
                });

            modelBuilder.Entity("MusicSite.Models.User", b =>
                {
                    b.Navigation("UserReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
